version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./default.env
    depends_on:
      - db
    networks:
      - backend
  db:
    image: postgres:latest
    expose: 
      - 5432
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Nasaandme2
      - POSTGRES_DB=postgres

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge